# Init

## Load

In [6]:
%cd ..
%pwd

/Users/wliao0504/code/clif

'/Users/wliao0504/code/clif'

In [7]:
from clifpy import MedicationAdminContinuous 

mac = MedicationAdminContinuous.from_file(
    data_directory = '/Users/wliao0504/code/clif/ucmc-clif-data/2.1.0',
    filetype = 'parquet',
    timezone = 'America/Chicago'
)

10:09:12 tables.medication_admin_continuous 📢 Initialized medication_admin_continuous table
10:09:12 tables.medication_admin_continuous 📢 Data directory: /Users/wliao0504/code/clif/ucmc-clif-data/2.1.0
10:09:12 tables.medication_admin_continuous 📢 File type: parquet
10:09:12 tables.medication_admin_continuous 📢 Timezone: America/Chicago
10:09:12 tables.medication_admin_continuous 📢 Output directory: /Users/wliao0504/code/clif/output
10:09:12 tables.medication_admin_continuous 📢 Loaded schema from /Users/wliao0504/code/clif/pyCLIF/clifpy/schemas/medication_admin_continuous_schema.yaml
10:09:12 tables.medication_admin_continuous 📢 Loaded outlier configuration

In [8]:
mac_df = mac.df

In [12]:
import pandas as pd
import duckdb

def find_mar_duplicates(meds_df: pd.DataFrame, ignore_zero_dose: bool = False) -> pd.DataFrame:
    print(f"Checking for duplicates to enable pivoting to wide format")

    med_category_column_name = 'med_category'
    # first drop exact-value, non-conflicting duplicates
    meds_df.drop_duplicates(subset=['hospitalization_id', 'admin_dttm', med_category_column_name, 'med_dose'], inplace=True)
    mask = meds_df.duplicated(subset=['hospitalization_id', 'admin_dttm', med_category_column_name], keep=False)
    dups = meds_df[mask]
    q = """
    SELECT *
        , combo: STRING_AGG(mar_action_name, '; ' ORDER BY mar_action_name) OVER (PARTITION BY hospitalization_id, med_category, admin_dttm)
    FROM dups
    """
    dups_w_combo = duckdb.sql(q).df()
    if not ignore_zero_dose:
        print(f"Found {len(dups_w_combo)} duplicate entries")
        return dups_w_combo.sort_values(by=['hospitalization_id', 'med_category', 'admin_dttm', 'mar_action_name'])
    non_zero_dups = dups_w_combo.query('med_dose > 0')
    mask = non_zero_dups.duplicated(subset=['hospitalization_id', 'admin_dttm', med_category_column_name], keep=False)
    non_zero_dups = non_zero_dups[mask]
    print(f"Found {len(non_zero_dups)} non-zero-dose duplicate entries")
    return non_zero_dups.sort_values(by=['hospitalization_id', 'med_category', 'admin_dttm', 'mar_action_name'])
    
def generate_combo_counts(dups_df: pd.DataFrame) -> pd.DataFrame:
    q = """
    SELECT 
        combo, COUNT(*) as count
    FROM dups_df
    GROUP BY combo
    ORDER BY count DESC
    """
    combo_counts = duckdb.sql(q).df()
    
    q = """
    SELECT *
    FROM dups_df
    WHERE combo in (
        SELECT combo FROM combo_counts 
        WHERE contains(combo, 'Given; Rate Change') OR contains(combo, 'Given; New Bag')
        --WHERE count > 100 AND NOT contains(combo, 'Canceled') AND NOT contains(combo, 'Verif')
    )
    """
    top_dups = duckdb.sql(q).df()
    
    return combo_counts, top_dups

dups = find_mar_duplicates(mac.df, ignore_zero_dose = True)#.head(10)
combo_counts, top_dups = generate_combo_counts(dups)

Checking for duplicates to enable pivoting to wide format
Found 1393 non-zero-dose duplicate entries

In [17]:
combo_counts

                                                combo  count
0                            Rate Verify; Rate Verify    444
1                            Rate Change; Rate Verify    200
2                             Canceled Entry; New Bag    182
3                         Canceled Entry; Rate Verify     80
4                            Rate Change; Rate Change     80
5                                New Bag; Rate Verify     66
6                                    New Bag; New Bag     60
7                                New Bag; Rate Change     50
8                         Canceled Entry; Rate Change     46
9                                     Missed; New Bag     32
10                                Missed; Rate Verify     28
11                                     Given; New Bag     22
12                          Canceled Entry; Restarted     14
13                                 Given; Rate Verify     14
14                                 Given; Rate Change     10
15                                 New Bag; Restarted      8
16                     Canceled Entry; Canceled Entry      6
17                            Given by Other; New Bag      6
18                                Missed; Rate Change      4
19                          Rate  Change; Rate Change      4
20                             Rate Verify; Restarted      4
21                          Rate  Change; Rate Verify      4
22            Canceled Entry; Canceled Entry; New Bag      3
23                                 Bolus; Rate Verify      2
24                                       Given; Given      2
25  24 hr total Insulin Pump Dose ; 24 hr total In...      2
26                              New Bag; Rate  Change      2
27                      Rate Verify; Restart Infusion      2
28                        Restart Infusion; Restarted      2
29                               Restarted; Restarted      2
30                             Rate Change; Restarted      2
31               Canceled Entry; New Bag; Rate Verify      2
32                        Given by Other; Rate Verify      2
33                                  New  Bag; New Bag      2
34                                     Missed; Missed      2
35                   New Bag; See Paper Documentation      2

In [24]:
import pandas as pd
import duckdb

def find_mar_duplicates(meds_df: pd.DataFrame, ignore_zero_dose: bool = False) -> pd.DataFrame:
    print(f"Checking for duplicates to enable pivoting to wide format")

    med_category_column_name = 'med_category'
    # first drop exact-value, non-conflicting duplicates
    meds_df.drop_duplicates(subset=['hospitalization_id', 'admin_dttm', med_category_column_name, 'med_dose'], inplace=True)
    mask = meds_df.duplicated(subset=['hospitalization_id', 'admin_dttm', med_category_column_name], keep=False)
    dups = meds_df[mask]
    q = """
    SELECT *
        , combo: STRING_AGG(mar_action_name, '; ' ORDER BY mar_action_name) OVER (PARTITION BY hospitalization_id, med_category, admin_dttm)
    FROM dups
    """
    dups_w_combo = duckdb.sql(q).df()
    if not ignore_zero_dose:
        print(f"Found {len(dups_w_combo)} duplicate entries")
        return dups_w_combo.sort_values(by=['hospitalization_id', 'med_category', 'admin_dttm', 'mar_action_name'])
    non_zero_dups = dups_w_combo.query('med_dose > 0')
    mask = non_zero_dups.duplicated(subset=['hospitalization_id', 'admin_dttm', med_category_column_name], keep=False)
    non_zero_dups = non_zero_dups[mask]
    print(f"Found {len(non_zero_dups)} non-zero-dose duplicate entries")
    return non_zero_dups.sort_values(by=['hospitalization_id', 'med_category', 'admin_dttm', 'mar_action_name'])
    
def generate_combo_counts(dups_df: pd.DataFrame) -> pd.DataFrame:
    q = """
    SELECT 
        combo, COUNT(*) as count
    FROM dups_df
    GROUP BY combo
    ORDER BY count DESC
    """
    combo_counts = duckdb.sql(q).df()
        
    return combo_counts

dups = find_mar_duplicates(mac.df, ignore_zero_dose = True)#.head(10)
combo_counts= generate_combo_counts(dups)

Checking for duplicates to enable pivoting to wide format
Found 1393 non-zero-dose duplicate entries

In [25]:
combo_counts

                                                combo  count
0                            Rate Verify; Rate Verify    444
1                            Rate Change; Rate Verify    200
2                             Canceled Entry; New Bag    182
3                            Rate Change; Rate Change     80
4                         Canceled Entry; Rate Verify     80
5                                New Bag; Rate Verify     66
6                                    New Bag; New Bag     60
7                                New Bag; Rate Change     50
8                         Canceled Entry; Rate Change     46
9                                     Missed; New Bag     32
10                                Missed; Rate Verify     28
11                                     Given; New Bag     22
12                          Canceled Entry; Restarted     14
13                                 Given; Rate Verify     14
14                                 Given; Rate Change     10
15                                 New Bag; Restarted      8
16                            Given by Other; New Bag      6
17                     Canceled Entry; Canceled Entry      6
18                          Rate  Change; Rate Verify      4
19                             Rate Verify; Restarted      4
20                                Missed; Rate Change      4
21                          Rate  Change; Rate Change      4
22            Canceled Entry; Canceled Entry; New Bag      3
23                                  New  Bag; New Bag      2
24                                 Bolus; Rate Verify      2
25                        Restart Infusion; Restarted      2
26                               Restarted; Restarted      2
27  24 hr total Insulin Pump Dose ; 24 hr total In...      2
28                             Rate Change; Restarted      2
29               Canceled Entry; New Bag; Rate Verify      2
30                        Given by Other; Rate Verify      2
31                                     Missed; Missed      2
32                   New Bag; See Paper Documentation      2
33                      Rate Verify; Restart Infusion      2
34                                       Given; Given      2
35                              New Bag; Rate  Change      2